name: Check
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: luizm/action-sh-checker@master
        env:
          SHELLCHECK_OPTS: -x
