name: 'CI/CD'
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: luizm/action-sh-checker@master
        env:
          SHELLCHECK_OPTS: -x
